modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="create_nuclear_war"
version="0.3.1"
displayName="Create: Nuclear War"
displayURL="https://modrinth.com/mod/createnuclearwar"
credits="uh me"
authors="ngbatz"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_nuclear_war]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.create_nuclear_war]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration